name: berrry-joyful

options:
  bundleIdPrefix: app.berrry
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  berrry-joyful:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - Sources
    resources:
      - Sources/berrry-joyful.icns
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: "Berrry Joyful"
        CFBundleShortVersionString: "0.5"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "14.0"
        NSPrincipalClass: NSApplication
        NSMainStoryboardFile: ""
        NSHumanReadableCopyright: "Copyright © 2025 Berrry Computer"
        NSSpeechRecognitionUsageDescription: "This app uses speech recognition to enable voice commands and voice-based text input for controlling your Mac with Joy-Con controllers."
        NSMicrophoneUsageDescription: "This app needs microphone access to listen for voice commands when using Joy-Con controllers."
        CFBundleIconFile: berrry-joyful.icns
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.berrry.joyful
        PRODUCT_NAME: "Berrry Joyful"
        INFOPLIST_KEY_NSMainStoryboardFile: ""
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        # Enable USB/HID access
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Sources/berrry-joyful.entitlements
